version: '3'

services:
  app:
    build: .
    volumes:
      - /Users/nolb/carpool/carpoolsvc:/workspaces
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://root:jam@db:5432/carpooldb
    command: sh -c "npm run migrate:latest && npm start"

  db:
    image: "postgres:16"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=jam
      - POSTGRES_DB=carpooldb
    ports:
      - "5432:5432"