version: '3.8'

services:
  app:
    build: .
    volumes:
      - /Users/nolb/carpool/carpoolsvc:/workspaces
      - /workspaces/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://root:jam@db:5432/carpooldb
      - JWT_SECRET=your_jwt_secret
    command: sh -c "npm run migrate:latest && npm start"

  db:
    image: "postgres:16"
    environment:
      - POSTGRES_DB=carpooldb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=jam
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d carpooldb"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: >
      sh -c "
        docker-entrypoint.sh postgres &
        until pg_isready -h localhost -p 5432; do
          echo waiting for database;
          sleep 2;
        done;
        psql -v ON_ERROR_STOP=1 --username root --dbname carpooldb -c 'CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";';
        wait
      "