version: '3'

services:
  app:
    volumes:
      - /Users/nolb/dev/proj/carpoolsvc:/workspaces
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db


  db:
    image: "postgres:16"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=jam
      - POSTGRES_DB=carpooldb
    ports:
      - "5432:5432"
